name: vpn test

on:
  push:
    branches:
      - master

jobs:
  vpn_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check ip
        run: curl ifconfig.me

      - name: install wg
        run: sudo apt install wireguard -y
        

      - name: Check version
        run: wg --version

      - name: Setup vpn
        env:
          VPN: ${{ secrets.VPN_TEST }}
        run: echo "$VPN">wg.conf

      - name: Check ip
        run: curl ifconfig.me
  
  
