name: Frontend Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/781583571951/locations/global/workloadIdentityPools/cricketgoo-github-identity-pool/providers/cricketgoo-github-idp"
          service_account: "cricketgoo-github-sa@cricketgoo.iam.gserviceaccount.com"
